#ifndef EMVGLOBAL_H
#define EMVGLOBAL_H
#include "EMV41.h"

#ifndef EXTGLOBAL
#define EXTGLOBAL extern
#endif

EXTGLOBAL TERMCONFIG        EMVConfig;
EXTGLOBAL UCHAR             ucTermCAPKNum;
EXTGLOBAL CAPK              TermCAPK[MAXTERMCAPKNUMS];
EXTGLOBAL UCHAR             ucTermAIDNum;
EXTGLOBAL TERMSUPPORTAPP    TermAID[MAXTERMAIDNUMS];
EXTGLOBAL UCHAR             ucIPKRevokeNum;
EXTGLOBAL IPKREVOKE         IPKRevoke[MAXIPKREVOKENUMS];
EXTGLOBAL UCHAR             ucExceptFileNum;
EXTGLOBAL EXCEPTPAN         ExceptFile[MAXEXCEPTFILENUMS];
EXTGLOBAL TRANSREQINFO      TransReqInfo;
//EXTGLOBAL EMVAIDPARAM       AIDParam[MAXTERMAIDNUMS];

#endif // EMVGLOBAL_H
